import cv2
import numpy as np
import random
from typing import List, Tuple, Dict, Union


HUE_FILTERS = {
    "red": [(0, 10), (170, 179)],
    "yellow": [(20, 35)],
    "green": [(35, 85)],
}


def get_colors(
    num_classes: int, filter_colors: bool = True
) -> List[Tuple[int, int, int]]:
    """Generates a list of visually distinct BGR colors for a given number of classes.

    This is often used to assign unique colors to different object classes
    when visualizing detection results. The colors are generated by evenly
    spacing hues in the HSV color space and then converting them to BGR.

    When `filter_colors=True`, the hue ranges corresponding to alert levels
    (red, yellow, green) are excluded to prevent overlap with the system’s
    predefined warning colors.
    Args:
        num_classes: The total number of unique classes for which colors
            are needed.
        filter_colors (bool, optional):
            Whether to exclude hues corresponding to alert colors
            (red, yellow, green). Defaults to True.

    Returns:
        A list of BGR color tuples, where each tuple is (Blue, Green, Red).
    """

    forbidden_ranges = []
    if filter_colors:
        for ranges in HUE_FILTERS.values():
            forbidden_ranges.extend(ranges)

    def is_in_forbidden(hue: int) -> bool:
        return any(start <= hue <= end for start, end in forbidden_ranges)

    def random_safe(base_hue: int) -> int:
        base_hue = int(base_hue)
        for _ in range(50):
            new_hue = (base_hue + random.randint(-10, 10)) % 180
            if not is_in_forbidden(new_hue):
                return new_hue
        while True:
            h = random.randint(0, 179)
            if not is_in_forbidden(h):
                return h

    # Generate visually distinct colors for classes
    hsv_tuples = [(x / num_classes, 1.0, 1.0) for x in range(num_classes)]
    colors = []

    for hsv in hsv_tuples:
        # Scale HSV values for cv2.cvtColor: H in [0,179], S and V in [0,255]
        hsv_scaled = np.array(
            [[[int(hsv[0] * 179), int(hsv[1] * 255), int(hsv[2] * 255)]]],
            dtype=np.uint8,
        )

        hue = hsv_scaled[0, 0, 0]
        if is_in_forbidden(hue):
            hsv_scaled[0, 0, 0] = random_safe(hue)

        bgr = cv2.cvtColor(hsv_scaled, cv2.COLOR_HSV2BGR)[0][0]
        colors.append(tuple(map(int, bgr)))

    return colors


def visualize(
    image: np.ndarray,
    bboxes: list,
    statuses: list,
    class_ids: List[Union[str, int]],
    cmap: Union[
        Dict[str, Tuple[int, int, int]],
        List[Tuple[int, int, int]]
    ],
) -> np.ndarray:
    """Draws BoundingBoxes, labels, and optionally skeletons on an image for visualization.

    Takes an image and lists of bounding boxes, scores, and class IDs, then
    draws them onto a copy of the image. The color of each box can be determined
    by a class name (if `cmap` is a dict) or by a class index (if `cmap` is a list).
    Labels include the class name/ID and the confidence score.

    Args:
        image: The input image (NumPy array) on which to draw.
        bboxes: A list of bounding boxes. Each box should be a list or tuple
            of `[x1, y1, x2, y2]` coordinates.
        scores: A list of confidence scores corresponding to each bounding box.
        class_ids: A list of class identifiers (string names or integer IDs)
            corresponding to each bounding box.
        cmap: A color map. Can be a dictionary mapping class names (str) to
            BGR color tuples, or a list of BGR color tuples indexed by class ID (int).

    Returns:
        A new NumPy array representing the image with visualizations drawn on it.

    Raises:
        ValueError: If `class_ids` contains a type that is incompatible with
            the type of `cmap` (e.g., string class ID with a list cmap).
    """
    image_draw = image.copy()
    img_h, img_w = image.shape[:2]

    if len(statuses) == 0:
        statuses = [""] * len(bboxes)

    assert len(bboxes) == len(statuses) == len(class_ids), (
        "Length of bboxes, statuses, and class_ids must be the same."
    )

    # Draw bounding boxes and labels
    for pred, label, cls in zip(bboxes, statuses, class_ids):
        # print("type(cls):", type(cls), cls)
        # print("type(cmap):", type(cmap), cmap)
        x1, y1, x2, y2 = pred
        if isinstance(cls, (int, str)) and isinstance(cmap, dict):
            box_color = cmap[cls] if cls in cmap else list(cmap.values())[0]
        elif isinstance(cls, int) and isinstance(cmap, list):
            box_color = cmap[cls] if cls < len(cmap) else cmap[cls % len(cmap)]
        else:
            raise ValueError("Invalid class ID or color mapping.")
        (label_w, label_h), baseline = cv2.getTextSize(
            label, cv2.FONT_HERSHEY_SIMPLEX, 0.6, 1
        )

        # Initial horizontal position for the label box.
        label_left = int(x1)
        label_right = label_left + label_w + 10

        # Adjust if label box exceeds the left boundary.
        if label_left < 0:
            label_left = 0
            label_right = label_left + label_w + 10

        # Adjust if label box exceeds the right boundary.
        if label_right > img_w:
            label_right = img_w
            label_left = img_w - (label_w + 10)
            # Ensure label_left is non-negative.
            if label_left < 0:
                label_left = 0
                label_right = label_left + label_w + 10

        # Determine vertical placement: default is above the bounding box.
        label_top = int(y1) - label_h - 8
        if label_top < 0:
            # Place below the box if it goes above the image.
            label_top = int(y1)
            label_bottom = label_top + label_h + 8
            text_org = (label_left + 5, label_top + label_h + 3)
        else:
            label_bottom = int(y1)
            text_org = (label_left + 5, int(y1) - 5)
            # Check if label box goes beyond the bottom edge of the image.
            if label_bottom > img_h:
                label_bottom = img_h
                label_top = img_h - (label_h + 8)
                text_org = (label_left + 5, label_top + label_h + 3)

        overlay = image_draw.copy()
        cv2.rectangle(
            overlay,
            (int(x1), int(y1)),
            (int(x2), int(y2)),
            box_color,
            2,
        )
        cv2.rectangle(
            overlay,
            (label_left, label_top),
            (label_right, label_bottom),
            box_color,
            -1,
        )
        alpha = 0.7
        cv2.addWeighted(overlay, alpha, image_draw, 1 - alpha, 0, image_draw)
        cv2.putText(
            image_draw,
            label,
            text_org,
            cv2.FONT_HERSHEY_SIMPLEX,
            0.6,
            (255, 255, 255),
            1,
            cv2.LINE_AA,
        )

    return image_draw
